import os
try:
    import re
    import telebot
except:
    os.system("pip install re")
    os.system("pip install telebot")
    
bot = telebot.TeleBot("5023634270:AAGkrTVKoZGQSmrpGdhMUYsr9QAg_0p0hQ0")

country_codes = {
    'Afghanistan 🇦🇫': ['+93'],
    'Albania 🇦🇱': ['+355'],
    'Algeria 🇩🇿': ['+213'],
    'American Samoa 🇦🇸': ['+1-684'],
    'Andorra 🇦🇩': ['+376'],
    'Angola 🇦🇴': ['+244'],
    'Anguilla 🇦🇮': ['+1-264'],
    'Antigua and Barbuda 🇦🇬': ['+1-268'],
    'Argentina 🇦🇷': ['+54'],
    'Armenia 🇦🇲': ['+374'],
    'Aruba 🇦🇼': ['+297'],
    'Australia 🇦🇺': ['+61'],
    'Austria 🇦🇹': ['+43'],
    'Azerbaijan 🇦🇿': ['+994'],
    'Bahamas 🇧🇸': ['+1-242'],
    'Bahrain 🇧🇭': ['+973'],
    'Bangladesh 🇧🇩': ['+880'],
    'Barbados 🇧🇧': ['+1-246'],
    'Belarus 🇧🇾': ['+375'],
    'Belgium 🇧🇪': ['+32'],
    'Belize 🇧🇿': ['+501'],
    'Benin 🇧🇯': ['+229'],
    'Bermuda 🇧🇲': ['+1-441'],
    'Bhutan 🇧🇹': ['+975'],
    'Bolivia 🇧🇴': ['+591'],
    'Bosnia and Herzegovina 🇧🇦': ['+387'],
    'Botswana 🇧🇼': ['+267'],
    'Brazil 🇧🇷': ['+55'],
    'Brunei 🇧🇳': ['+673'],
    'Bulgaria 🇧🇬': ['+359'],
    'Burkina Faso 🇧🇫': ['+226'],
    'Burundi 🇧🇮': ['+257'],
    'Cambodia 🇰🇭': ['+855'],
    'Cameroon 🇨🇲': ['+237'],
    'Canada 🇨🇦': ['+1'],
    'Cape Verde 🇨🇻': ['+238'],
    'Cayman Islands 🇰🇾': ['+1-345'],
    'Central African Republic 🇨🇫': ['+236'],
    'Chad 🇹🇩': ['+235'],
    'Chile 🇨🇱': ['+56'],
    'China 🇨🇳': ['+86'],
    'Colombia 🇨🇴': ['+57'],
    'Comoros 🇰🇲': ['+269'],
    'Congo 🇨🇬': ['+242'],
    'Democratic Republic of the Congo 🇨🇩': ['+243'],
    'Costa Rica 🇨🇷': ['+506'],
    'Ivory Coast 🇨🇮': ['+225'],
    'Croatia 🇭🇷': ['+385'],
    'Cuba 🇨🇺': ['+53'],
    'Cyprus 🇨🇾': ['+357'],
    'Czech Republic 🇨🇿': ['+420'],
    'Denmark 🇩🇰': ['+45'],
    'Djibouti 🇩🇯': ['+253'],
    'Dominica 🇩🇲': ['+1-767'],
    'Dominican Republic 🇩🇴': ['+1-809', '+1-829', '+1-849'],
    'Ecuador 🇪🇨': ['+593'],
    'Egypt 🇪🇬': ['+20'],
    'El Salvador 🇸🇻': ['+503'],
    'Equatorial Guinea 🇬🇶': ['+240'],
    'Eritrea 🇪🇷': ['+291'],
    'Estonia 🇪🇪': ['+372'],
    'Eswatini 🇸🇿': ['+268'],
    'Ethiopia 🇪🇹': ['+251'],
    'Fiji 🇫🇯': ['+679'],
    'Finland 🇫🇮': ['+358'],
    'France 🇫🇷': ['+33'],
    'Gabon 🇬🇦': ['+241'],
    'Gambia 🇬🇲': ['+220'],
    'Georgia 🇬🇪': ['+995'],
    'Germany 🇩🇪': ['+49'],
    'Ghana 🇬🇭': ['+233'],
    'Greece 🇬🇷': ['+30'],
    'Grenada 🇬🇩': ['+1-473'],
    'Guatemala 🇬🇹': ['+502'],
    'Guinea 🇬🇳': ['+224'],
    'Guinea-Bissau 🇬🇼': ['+245'],
    'Guyana 🇬🇾': ['+592'],
    'Haiti 🇭🇹': ['+509'],
    'Honduras 🇭🇳': ['+504'],
    'Hungary 🇭🇺': ['+36'],
    'Iceland 🇮🇸': ['+354'],
    'India 🇮🇳': ['+91'],
    'Indonesia 🇮🇩': ['+62'],
    'Iran 🇮🇷': ['+98'],
    'Iraq 🇮🇶': ['+964'],
    'Ireland 🇮🇪': ['+353'],
    'Israel 🇮🇱': ['+972'],
    'Italy 🇮🇹': ['+39'],
    'Jamaica 🇯🇲': ['+1-876'],
    'Japan 🇯🇵': ['+81'],
    'Jordan 🇯🇴': ['+962'],
    'Kazakhstan 🇰🇿': ['+7'],
    'Kenya 🇰🇪': ['+254'],
    'Kiribati 🇰🇮': ['+686'],
    'North Korea 🇰🇵': ['+850'],
    'South Korea 🇰🇷': ['+82'],
    'Kuwait 🇰🇼': ['+965'],
    'Kyrgyzstan 🇰🇬': ['+996'],
    'Laos 🇱🇦': ['+856'],
    'Latvia 🇱🇻': ['+371'],
    'Lebanon 🇱🇧': ['+961'],
    'Lesotho 🇱🇸': ['+266'],
    'Liberia 🇱🇷': ['+231'],
    'Libya 🇱🇾': ['+218'],
    'Liechtenstein 🇱🇮': ['+423'],
    'Lithuania 🇱🇹': ['+370'],
    'Luxembourg 🇱🇺': ['+352'],
    'North Macedonia 🇲🇰': ['+389'],
    'Madagascar 🇲🇬': ['+261'],
    'Malawi 🇲🇼': ['+265'],
    'Malaysia 🇲🇾': ['+60'],
    'Maldives 🇲v': ['+960'],
    'Mali 🇲🇱': ['+223'],
    'Malta 🇲🇹': ['+356'],
    'Marshall Islands 🇲🇭': ['+692'],
    'Mauritania 🇲🇷': ['+222'],
    'Mauritius 🇲🇺': ['+230'],
    'Mexico 🇲🇽': ['+52'],
    'Micronesia 🇫🇲': ['+691'],
    'Moldova 🇲🇩': ['+373'],
    'Monaco 🇲🇨': ['+377'],
    'Mongolia 🇲🇳': ['+976'],
    'Montenegro 🇲🇪': ['+382'],
    'Morocco 🇲🇦': ['+212'],
    'Mozambique 🇲🇿': ['+258'],
    'Myanmar 🇲🇲': ['+95'],
    'Namibia 🇳🇦': ['+264'],
    'Nauru 🇳🇷': ['+674'],
    'Nepal 🇳🇵': ['+977'],
    'Netherlands 🇳🇱': ['+31'],
    'New Zealand 🇳🇿': ['+64'],
    'Nicaragua 🇳🇮': ['+505'],
    'Niger 🇳🇪': ['+227'],
    'Nigeria 🇳🇬': ['+234'],
    'Norway 🇳🇴': ['+47'],
    'Oman 🇴🇲': ['+968'],
    'Pakistan 🇵🇰': ['+92'],
    'Palau 🇵🇼': ['+680'],
    'Panama 🇵🇦': ['+507'],
    'Papua New Guinea 🇵🇬': ['+675'],
    'Paraguay 🇵🇾': ['+595'],
    'Peru 🇵🇪': ['+51'],
    'Philippines 🇵🇭': ['+63'],
    'Poland 🇵🇱': ['+48'],
    'Portugal 🇵🇹': ['+351'],
    'Qatar 🇶🇦': ['+974'],
    'Romania 🇷🇴': ['+40'],
    'Russia 🇷🇺': ['+7'],
    'Rwanda 🇷🇼': ['+250'],
    'Saint Kitts and Nevis 🇰🇳': ['+1-869'],
    'Saint Lucia 🇱🇨': ['+1-758'],
    'Saint Vincent and the Grenadines 🇻🇨': ['+1-784'],
    'Samoa 🇼🇸': ['+685'],
    'San Marino 🇸🇲': ['+378'],
    'Sao Tome and Principe 🇸🇹': ['+239'],
    'Saudi Arabia 🇸🇦': ['+966'],
    'Senegal 🇸🇳': ['+221'],
    'Serbia 🇷🇸': ['+381'],
    'Seychelles 🇸🇨': ['+248'],
    'Sierra Leone 🇸L': ['+232'],
    'Singapore 🇸🇬': ['+65'],
    'Slovakia 🇸🇰': ['+421'],
    'Slovenia 🇸🇮': ['+386'],
    'Solomon Islands 🇸B': ['+677'],
    'Somalia 🇸O': ['+252'],
    'South Africa 🇿🇦': ['+27'],
    'Spain 🇪🇸': ['+34'],
    'Sri Lanka 🇱🇰': ['+94'],
    'Sudan 🇸D': ['+249'],
    'Suriname 🇸R': ['+597'],
    'Sweden 🇸E': ['+46'],
    'Switzerland 🇨H': ['+41'],
    'Syria 🇸Y': ['+963'],
    'Taiwan 🇹🇼': ['+886'],
    'Tajikistan 🇹J': ['+992'],
    'Tanzania 🇹Z': ['+255'],
    'Thailand 🇹H': ['+66'],
    'Timor-Leste 🇹L': ['+670'],
    'Togo 🇹G': ['+228'],
    'Tonga 🇹O': ['+676'],
    'Trinidad and Tobago 🇹T': ['+1-868'],
    'Tunisia 🇹N': ['+216'],
    'Turkey 🇹R': ['+90'],
    'Turkmenistan 🇹M': ['+993'],
    'Tuvalu 🇹V': ['+688'],
    'Uganda 🇺G': ['+256'],
    'Ukraine 🇺A': ['+380'],
    'United Arab Emirates 🇦E': ['+971'],
    'United Kingdom 🇬🇧': ['+44'],
    'Uruguay 🇺Y': ['+598'],
    'Uzbekistan 🇺Z': ['+998'],
    'Vanuatu 🇻U': ['+678'],
    'Vatican City 🇻A': ['+39'],
    'Venezuela 🇻E': ['+58'],
    'Vietnam 🇻N': ['+84'],
    'Yemen 🇾E': ['+967'],
    'Zambia 🇿M': ['+260'],
    'Zimbabwe 🇿W': ['+263']
}

def find_country(phone_number):
    phone_number = re.sub(r'\D', '', phone_number)
    for country, codes in country_codes.items():
        for code in codes:
            if phone_number.startswith(code.strip('+')):
                return country
    return "Unknown"

@bot.message_handler(commands=['start'])
def send_welcome(message):
    bot.reply_to(message, "Welcome! Please enter a phone number to get the corresponding country. Or type /ex to quit.")

@bot.message_handler(func=lambda message: True)
def echo_all(message):
    if message.text.lower() == "/ex":
        bot.reply_to(message, "Bot is shutting down.")
        raise SystemExit()
    else:
        phone_number = message.text
        if not phone_number.startswith("+"):
            phone_number = "+" + phone_number
        country = find_country(phone_number)
        bot.reply_to(message, f"Country: {country}")

bot.polling()
